### PR TITLE
add initial files from RNASeq-CWLTools

### PR DESCRIPTION
**Pull request by kdaily**
Uses the naming convention for the repo set forth by @jaeddy, which I think is good (and I used previously as well).

### CODE REVIEW

**Review by wpoehlm — APPROVED** [review]
This looks good.  In the event that a given software tool (ie picard tools) is used for many different cwl tools, are we OK with this organization?

**Comment by kdaily** [comment]
I almost posted this question in my commit. If there are multiple 'tools' for a single application (even cell ranger has multiple), how should this be organized? I think we would set up multiple dockstore tools from the same repo, as they would rely on the same underlying container. I put the CWL in the top level directory, but maybe they should be down a level.

**Comment by wpoehlm** [comment]
> 
> 
> I almost posted this question in my commit. If there are multiple 'tools' for a single application (even cell ranger has multiple), how should this be organized? I think we would set up multiple dockstore tools from the same repo, as they would rely on the same underlying container. I put the CWL in the top level directory, but maybe they should be down a level.

I agree that we should have multiple dockstore tools from the same github repo, it would be excessive to have a single github repo for each CWL file.  I think the top level directory is alright, but maybe nesting those in a CWL directory would make more sense

**Comment by kdaily** [comment]
Merging for now, but can address this before connecting to dockstore!

**Pull request merged**
